//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.SaleOrders = new HashSet<SaleOrder>();
        }
    
        public int cust_id { get; set; }
        public string cust_name { get; set; }
        public string cust_address { get; set; }
        public string cust_phone { get; set; }
    
        public virtual ICollection<SaleOrder> SaleOrders { get; set; }
    }
}
