//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportOrder
    {
        public ImportOrder()
        {
            this.ImportOrderItems = new HashSet<ImportOrderItem>();
        }
    
        public int order_id { get; set; }
        public int user_id { get; set; }
        public decimal total_price { get; set; }
        public System.DateTime date_import { get; set; }
        public string order_status { get; set; }
    
        public virtual ICollection<ImportOrderItem> ImportOrderItems { get; set; }
        public virtual User User { get; set; }
    }
}
