//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ImportOrderItems = new HashSet<ImportOrderItem>();
            this.SaleOrderItems = new HashSet<SaleOrderItem>();
            this.Stocks = new HashSet<Stock>();
        }
    
        public string prod_id { get; set; }
        public string prod_name { get; set; }
        public int quantity_control { get; set; }
        public int quantity_by_unit { get; set; }
        public int quantity_by_stock { get; set; }
        public decimal sale_price_by_unit { get; set; }
        public decimal sale_price_by_stock { get; set; }
        public System.DateTime date_added { get; set; }
        public System.DateTime date_modified { get; set; }
    
        public virtual ICollection<ImportOrderItem> ImportOrderItems { get; set; }
        public virtual ICollection<SaleOrderItem> SaleOrderItems { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
