//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleOrder
    {
        public SaleOrder()
        {
            this.SaleOrderItems = new HashSet<SaleOrderItem>();
        }
    
        public int order_id { get; set; }
        public int cust_id { get; set; }
        public int user_id { get; set; }
        public decimal total_price { get; set; }
        public decimal taken_money { get; set; }
        public System.DateTime date_created { get; set; }
        public System.DateTime date_ship { get; set; }
        public string order_status { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<SaleOrderItem> SaleOrderItems { get; set; }
        public virtual User User { get; set; }
    }
}
